services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - ask
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_AGREE: "true"
      TZ: UTC
      CADDY_EMAIL: ${CADDY_EMAIL:-you@example.com}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./sites:/srv/sites:ro
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:80 >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3

  ask:
    build: ./ask
    restart: unless-stopped
    volumes:
      - ./sites:/srv/sites:ro
    environment:
      METRICS_SECRET: ${METRICS_SECRET:-change-this-secret-key}
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:8080/health >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3

  php-fpm:
    image: php:8.2-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./sites:/srv/sites:ro
      - ./monitoring/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-monitoring.conf:ro
    environment:
      TZ: UTC
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3

  # Monitoring services (for external Grafana to scrape)
  # SECURITY: These ports are restricted to internal networks only
  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    # Restrict to internal networks only - remove external port exposure
    # ports:
    #   - "9100:9100"
    networks:
      - monitoring
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:9100/metrics >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3

  php-fpm-exporter:
    image: hipages/php-fpm_exporter:latest
    restart: unless-stopped
    # Restrict to internal networks only - remove external port exposure
    # ports:
    #   - "9253:9253"
    networks:
      - monitoring
    environment:
      PHP_FPM_SCRAPE_URI: "tcp://php-fpm:9000/status"
    depends_on:
      - php-fpm
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:9253/metrics >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  caddy_data:
  caddy_config:
  caddy_logs:

networks:
  monitoring:
    driver: bridge
    internal: true

