services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_AGREE: "true"
      TZ: UTC
      CADDY_EMAIL: ${CADDY_EMAIL:-you@example.com}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./sites:/srv/sites:ro
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:80 >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  caddy_data:
  caddy_config:
  caddy_logs:

